[package]
name = "plugin_generator_demo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
crate-type = ["cdylib"]

[dependencies]
wasmedge_plugin_sdk = "0.1.0"

[workspace]
members = ["demo_wasm"]
